name: Docker Image CI App 4

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd dirichlet_dash_app04
        docker build . --file Dockerfile --tag dirichlet-docker:$(date +%s)
